version: 2.1
commands:
  set_up_git:
    steps:
      - checkout
      - run:
          name: setup git user
          command: |
            git config user.email $GITHUB_EMAIL
            git config user.name $GITHUB_USER
  create_pr:
    steps:
      - checkout
      - run:
          name: Create and push changes
          command: |
            git switch -c $BRANCH_NAME
            echo "Some changes" >> file.txt
            git add .
            git commit -m "Update file.txt"
            git push origin $BRANCH_NAME
      - run:
          name: Create pull request
          # ref: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request
          command: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ksrnnb/ci_create_pr/pulls \
            -d '{"title": "create PR test", "body": "PR body dayo", "head": "$BRANCH_NAME", "base": "main"}'
jobs:
  create_pr_job:
    docker:
      - image: cimg/base:stable
    environment:
      BRANCH_NAME: "hoge_service_${CIRCLE_TAG}"
    steps:
      - set_up_git
      - create_pr

workflows:
  version: 2
  build:
    jobs:
      - create_pr_job:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
