version: 2.1
commands:
  install_commands:
    steps:
      - run:
          name: install commands
          command: |
            apk add curl jq yq git bash openssh
  set_up_git:
    steps:
      - checkout
      - run:
          name: setup git user
          command: |
            git config user.email $GITHUB_EMAIL
            git config user.name $GITHUB_USER
  create_pr:
    steps:
      - checkout
      - run:
          name: release_pr
          command: |
            service_name=$(echo ${CIRCLE_TAG} | cut -d/ -f2)
            version=$(echo $CIRCLE_TAG | cut -d/ -f3)
            make microservices/app/release_pr SERVICE_NAME=${service_name} VERSION=${version} GITHUB_TOKEN=${GITHUB_TOKEN}
jobs:
  release_pr_job:
    docker:
      - image: alpine:3.19.0
    shell: /bin/sh -leo pipefail
    environment:
      BASH_ENV: /etc/profile
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:7p8XHnZsyzH7w0g/mBhp4dEeHNO6gPyTV5io5esfZPs"
      - install_commands
      - set_up_git
      - release_pr

workflows:
  version: 2
  build:
    jobs:
      - release_pr_job:
          filters:
            tags:
              only: /^microservices.*/
            branches:
              ignore: /.*/
