apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: piyo
    tags.datadoghq.com/version: "0.1.3"
  name: piyo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piyo
  template:
    metadata:
      labels:
        app: piyo
        tags.datadoghq.com/version: "0.1.3"
    spec:
      containers:
        - name: piyo
          image: hogehogepiyopiyo/foo/bar:0.1.3
        - name: nginx
          image: nginx:1.26.0
