name: update service label

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get changed directories
        id: get_changed_dirs
        run: |
          git fetch origin ${{ github.base_ref }}
          changed_dirs=$(git diff --name-only origin/${{ github.base_ref }} HEAD -- microservices | awk -F'/' '{print $2}' | sort -u | xargs)
          echo "Changed dirs: $changed_dirs"
          echo "changed_dirs=$changed_dirs" >> $GITHUB_OUTPUT

      - name: Use outputs in next steps
        uses: actions/github-script@v6
        with:
          script: |
            const labelsToAdd = new Set();
            const labelColor = '0052CD';
            const changedDirs = "${{ steps.get_changed_dirs.outputs.changed_dirs }}".split(" ");

            console.log(changedDirs)

            const currentLabels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });


            // filter by color to get services' label
            const currentServiceLabelNames = currentLabels.data.filter(label => label.color === labelColor).map(label => label.name);
            const changedServiceNames = new Set();

            changedDirs.forEach((serviceName) => {
              changedServiceNames.add(serviceName);
              if (!currentServiceLabelNames.includes(serviceName)) {
                labelsToAdd.add(serviceName);
              }
            });

            const labelsToRemove = new Set(
              [...currentServiceLabelNames].filter(currentServiceLabelName => !changedServiceNames.has(currentServiceLabelName))
            );

            // Output log
            console.log("currentServiceLabelNames", currentServiceLabelNames);
            console.log("changedServiceNames", changedServiceNames);
            console.log("labelsToAdd", labelsToAdd);
            console.log("labelsToRemove", labelsToRemove);
