name: update service label

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            microservices
      - name: Get all changed microservices files
        id: changed-microservice-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: "true"
          dir_names_max_depth: 2
          exclude_submodules: "true"
          files: |
            microservices/**
      - name: Use outputs in next steps
        uses: actions/github-script@v6
        with:
          script: |
            const labelsToAdd = new Set();
            const labelColor = '0052CD';
            const changedFiles = "${{ steps.changed-microservice-files.outputs.all_changed_files }}".split(" ");

            console.log(changedFiles)

            const currentLabels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });


            // filter by color to get services' label
            const currentServiceLabelNames = currentLabels.data.filter(label => label.color === labelColor).map(label => label.name);
            const changedServiceNames = new Set();

            changedFiles.forEach((file) => {
              const directories = file.split('/');
              if (directories.length > 1) {
                // file => microservices/{service_name}/**
                // directories => ["microservices", {service_name}, ...]
                const serviceName = directories[1];
                changedServiceNames.add(serviceName);
                // https://docs.github.com/ja/rest/issues/labels?apiVersion=2022-11-28#list-labels-for-an-issue
                if (!currentServiceLabelNames.includes(serviceName)) {
                  labelsToAdd.add(serviceName);
                }
              }
            });

            const labelsToRemove = new Set(
              [...currentServiceLabelNames].filter(currentServiceLabelName => !changedServiceNames.has(currentServiceLabelName))
            );

            // Output log
            console.log("currentServiceLabelNames", currentServiceLabelNames);
            console.log("changedServiceNames", changedServiceNames);
            console.log("labelsToAdd", labelsToAdd);
            console.log("labelsToRemove", labelsToRemove);

            if (labelsToAdd.size === 0 && labelsToRemove.size === 0) {
              return;
            }

            if (labelsToAdd.size > 0) {
              Array.from(labelsToAdd).forEach(async (label) => {
                // Create a service label
                try {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: label,
                    color: labelColor
                  });
                } catch (error) {
                  // status 422 means that a label has already created
                  // https://docs.github.com/ja/rest/issues/labels?apiVersion=2022-11-28#create-a-label--status-codes
                  if (error.status !== 422) throw error;
                }
              });

              // Assign new service labels
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [...labelsToAdd]
              });
            }

            // remove unnecessary service labels
            if (labelsToRemove.size > 0) {
              Array.from(labelsToRemove).forEach(async (label) => {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                name: label
              });
            })}
