name: Update Release Draft

on:
  pull_request:
    types: [closed]

jobs:
  update-release-draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create or Update Release Draft
        uses: actions/github-script@v7
        with:
          script: |
            const labelColor = '0052CD';

            const currentLabels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            })

            // filter by color to get services' label
            const currentServiceLabelNames = currentLabels.data.filter(label => label.color === labelColor).map(label => label.name);

            // paginate method get all data
            // https://docs.github.com/ja/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28#example-using-the-octokitjs-pagination-method
            const releases = await github.paginate(github.rest.repos.listReleases, {
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const draftReleases = releases.filter(release => release.draft && currentServiceLabelNames.includes(release.name));

            const servicesToCreate = currentServiceLabelNames.filter(serviceName => draftReleases.find(release => release.name === serviceName) === undefined)
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            const authorId = context.payload.pull_request.user.login;
            const newBody = `- ${prTitle} by @${authorId} in #${prNumber}`;

            console.log("draftReleases", draftReleases);
            console.log("currentServiceLabelNames", currentServiceLabelNames);
            console.log("servicesToCreate", servicesToCreate);
            console.log("prTitle", prTitle);
            console.log("prNumber", prNumber);

            // update draft release
            for (const draftRelease of draftReleases) {
                const body = `${draftRelease.body}\n${newBody}`;
                await github.rest.repos.updateRelease({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    release_id: draftRelease.id,
                    body
                });
            }

            // Create new draft
            for (const service of servicesToCreate) {
                await github.rest.repos.createRelease({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    tag_name: `${service}-draft-${new Date().toISOString()}`,
                    name: service,
                    body: newBody,
                    draft: true
                });
            }
