name: get changed dir

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get changed directories
        id: get_changed_dirs
        run: |
          git fetch origin ${{ github.base_ref }}
          changed_dirs=$(git diff --name-only origin/${{ github.base_ref }} HEAD -- microservices | awk -F'/' '{print $2}' | sort -u | xargs)
          echo "Changed dirs: $changed_dirs"
          echo "changed_dirs=$changed_dirs" >> $GITHUB_OUTPUT

      - name: Use outputs in next steps
        run: |
          echo "Changed directories are: ${{ steps.get_changed_dirs.outputs.changed_dirs }}"
