name: get changed dir

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get changed directories
        id: get_changed_dirs
        run: |
          echo "github.base_ref: ${{ github.base_ref }}"
          git fetch origin ${{ github.base_ref }}
          echo "branch: origin/${{ github.base_ref }}"
          base_commit=$(git merge-base origin/main HEAD)
          echo "base commit: $base_commit"
          changed_dirs=$(git diff --name-only $base_commit HEAD -- microservices | awk -F'/' '{print $2}' | sort -u | xargs)
          echo "Changed dirs: $changed_dirs"
          echo "changed_dirs=$changed_dirs" >> $GITHUB_OUTPUT

      - name: Use outputs in next steps
        run: |
          echo "Changed directories are: ${{ steps.get_changed_dirs.outputs.changed_dirs }}"
